// <auto-generated />
using FitnessTrainerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitnessTrainerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525000000_SeedFoodProducts")]
    partial class SeedFoodProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
